GET https://json-storage-c5bh.onrender.com
content-type: application/json

###

POST https://json-storage-c5bh.onrender.com
content-type: application/json

###

{
    "player": "teste",
    "score": 50
}